spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: 1.0

loans:
  messages: "This is the Loans Microservice in IndiaBank local Prod APIs"
  contactDetails:
    name: "Ramya - Senior Support Engineer"
    email: "ramya@indiabank.com"
  onCallSupport:
    - (+91) 3622000378
    - (+1) 5555-3333-222